name: MetricsUpdater

# Controls when the action will run. 
on:
  #Schedule updates (every hour)
  schedule: [{cron: "*/30 * * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{secrets.METRICS_TOKEN}}

          #Options
          user: UnmappedStack
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Australia

          plugin_introduction: yes
          plugin_introduction_title: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_lines: yes

          plugin_languages: yes
          plugin_languages_ignored: cmake, bash
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 2%

          plugin_traffic: yes

          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 0
